### ISSUE TITLE
Verbose of downloaded files

### ISSUE THREAD

**Issue by davivc** [dbarneche/noaaErddap#1]
Is there any way to show the file size and how much was downloaded, like a verbose method? There is a verbose() function that is possible to call using httr::GET but I couldn't get that working with this package.

**Comment by davivc** [comment]
Another issue was timeout of curl_fetch_disk. I don't know what is your rig there but I'm trying to fectch SST data from 1996 to 2017 using my laptop (Win10 i7 16GB RAM with 3.5mbps from my ISP).

**Comment by davivc** [comment]
This is what debug shows me when I ran the following:

dat  <-  data.frame(year = 1996:2016, month = 12)
nppFiles  <-  ddply(dat, .(year, month), function(x, type)  {
  data.frame(links = erddapDownload(x$year, x$month, type, overwrite = TRUE), stringsAsFactors = FALSE)
}, type = 'sst')

Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached 
14. curl::curl_fetch_disk(url, x$path, handle = handle) 
13. request_fetch.write_disk(req$output, req$url, handle) 
12. request_fetch(req$output, req$url, handle) 
11. request_perform(req, hu$handle$handle) 
10. httr::GET(typeLink, httr::write_disk(filePath, overwrite = overwrite), ...) 
9. erddapGet(type, filePath, firstDay, overwrite, ...) 
8. erddapDownload(x$year, x$month, type, overwrite = TRUE) 
7. data.frame(links = erddapDownload(x$year, x$month, type, overwrite = TRUE),  stringsAsFactors = FALSE) 
6. .fun(piece, ...) 
5. (function (i) 
{
    piece <- pieces[[i]]
    if (.inform) { ... 
4. loop_apply(n, do.ply) 
3. llply(.data = .data, .fun = .fun, ..., .progress = .progress, 
    .inform = .inform, .parallel = .parallel, .paropts = .paropts) 
2. ldply(.data = pieces, .fun = .fun, ..., .progress = .progress, 
    .inform = .inform, .parallel = .parallel, .paropts = .paropts) 
1. ddply(dat, .(year, month), function(x, type) {
    data.frame(links = erddapDownload(x$year, x$month, type, 
        overwrite = TRUE), stringsAsFactors = FALSE)
}, type = "sst")

**Comment by dbarneche** [comment]
Thanks for your comments @davivc Apologies for taking so long to reply to this.

I'll check in the near future if it is possible to implement the `verbose` argument.

As for `curl_fetch_disk`, did it happen with the specs you provided only (i.e. sst, al months between 1996-2016)? If you try shorter or longer series will it work? Also, sometimes the NOAA server is down for maintenance, so if you try again after another day or two it might work. Please let me know so I can chase that up.
